package br.com.bruno.goiascola

enum class ProductsEnum {
    ARGAMASSA_POLIMERICA_BARRICA_50KG,
    ARGAMASSA_POLIMERICA_SACO_15KG,
    ARGAMASSA_POLIMERICA_BISNAGA_3KG,
    REBOCO_PLUS_BALDE_30_KG,
    CHAPISCO_ROLADO_BARRICA_40KG
}